options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: asset-dashboard-426812
steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - build
  - asia-northeast3-docker.pkg.dev/asset-dashboard-426812/buildpacks-docker-repo/crocodile-app
  - --builder
  - gcr.io/buildpacks/builder:latest
  - --network
  - cloudbuild