"""Add asset and liability details to Snapshot model

Revision ID: 938d5e7cef0f
Revises: eff6b5ef6928
Create Date: 2024-06-16 22:29:23.206436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938d5e7cef0f'
down_revision = 'eff6b5ef6928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
